<style>
    table, th, td {
        border: 1px solid #ddd !important;
    }
</style>
<section>
    <img src="http://www.parsonline.com/data/uploaded_files/1486540967-3.jpg" width="100%" alt="لیست سایت ها با ترافیک داخلی"/>
</section>
<div class="container-fluid blue-ribbon text-center">
    <h1 class="font_large" style="color: #fdfdfd /*#fbf9f9*/;">لیست سایت ها با ترافیک داخلی</h1>
</div>
<section>
    <div class="container-fluid text-justify" style="background-color: #d9d9d9; padding: 30px 0;">
        <div class="container font_medium padding_10">
            <p>فقط وب سایتهای درج شده در کادر زیر، ترافیکشان داخلی محسوب می شود.</p>
        </div>
        <div class="container white_panel">
            <div class="table-responsive">
                <table class="table table-hover table-striped" style="max-width: none !important;">
                    <tr style="color: #005baa">
                        <th>تخصصی و انجمن</th>
                        <th>دانلود و ابزار وب</th>
                        <th>خبرگزاری</th>
                        <th>سرویس بلاگ</th>
                        <th>موزیک و ویدئو</th>
                        <th>سرگرمی</th>
                        <th>خدماتی</th>
                        <th>دانشگاه ها و موسسات آموزشی</th>
                        <th>بانک ها</th>
                        <th>تبلیغاتی</th>
                    </tr>
                    <tr>
                        <td>varzesh3.com</td>
                        <td>yasdl.com</td>
                        <td>tabnak.ir</td>
                        <td>mihanblog.com</td>
                        <td>namasha.com</td>
                        <td>pars-cup.com</td>
                        <td style="direction: ltr;text-align: right">780.ir</td>
                        <td>uast.ac.ir</td>
                        <td>bankmellat.ir</td>
                        <td>lordpopup.com</td>
                    </tr>
                    <tr>
                        <td>picofile.com</td>
                        <td>cafebazaar.ir</td>
                        <td>mehrnews.com</td>
                        <td>blog.ir</td>
                        <td>toneback.ir</td>
                        <td>tebyan.net</td>
                        <td>club.parsonline.com</td>
                        <td>ut.ac.ir</td>
                        <td>bmi.ir</td>
                        <td>divar.ir</td>
                    </tr>
                    <tr>
                        <td>zoomit.ir</td>
                        <td>asandl.com</td>
                        <td>khabaronline.ir</td>
                        <td>persianblog.ir</td>
                        <td>tv.parsonline.com</td>
                        <td>namnak.com</td>
                        <td>digikala.com</td>
                        <td>kanoon.ir</td>
                        <td>bpi.ir</td>
                        <td>bama.ir</td>
                    </tr>
                    <tr>
                        <td>zoomg.ir</td>
                        <td>downloadha.com</td>
                        <td>shahrekhabar.com</td>
                        <td>rozblog.com</td>
                        <td>aionet.ir</td>
                        <td>persianv.com</td>
                        <td>shaparak.ir</td>
                        <td>tvu.ac.ir</td>
                        <td>sb24.com</td>
                        <td>sheypoor.com</td>
                    </tr>
                    <tr>
                        <td>90tv.ir</td>
                        <td>vatandownload.com</td>
                        <td>yjc.ir</td>
                        <td>loxblog.com</td>
                        <td>aparat.com</td>
                        <td>facenama.com</td>
                        <td>tamin.ir</td>
                        <td>pnu.ac.ir</td>
                        <td>tejaratbank.ir</td>
                        <td>popkade.ir</td>
                    </tr>
                    <tr>
                        <td>gsm.ir</td>
                        <td>sarzamindownload.com</td>
                        <td>farsnews.com</td>
                        <td>parsiblog.com</td>
                        <td>musiceiranian.ir</td>
                        <td>cloob.com</td>
                        <td>irib.ir</td>
                        <td>um.ac.ir</td>
                        <td>cbi.ir</td>
                        <td>irpopup.ir</td>
                    </tr>
                    <tr>
                        <td>1varzesh.com</td>
                        <td></td>
                        <td>asriran.com</td>
                        <td>niniweblog.com</td>
                        <td>mibinim.com</td>
                        <td>tarafdari.com</td>
                        <td>zarinpal.com</td>
                        <td>hawzah.net</td>
                        <td>bsi.ir</td>
                        <td>anetwork.ir</td>
                    </tr>
                    <tr>
                        <td>hamyarwp.com</td>
                        <td></td>
                        <td>isna.ir</td>
                        <td></td>
                        <td>filimo.com</td>
                        <td>irannaz.com</td>
                        <td>medu.ir</td>
                        <td>roshd.ir</td>
                        <td>ebanksepah.ir</td>
                        <td>sabavision.com</td>
                    </tr>
                    <tr>
                        <td>abadis.ir</td>
                        <td></td>
                        <td>khabaronline.ir</td>
                        <td></td>
                        <td>filmnet.ir</td>
                        <td>digiato.com</td>
                        <td>enamad.ir</td>
                        <td>aut.ac.ir</td>
                        <td>enbank.net</td>
                        <td>rahnama.com</td>
                    </tr>
                    <tr>
                        <td>meghdadit.com</td>
                        <td></td>
                        <td>mehrnews.com</td>
                        <td></td>
                        <td>iseema.ir</td>
                        <td>rasekhoon.net</td>
                        <td>rightel.ir</td>
                        <td>iauctb.ac.ir</td>
                        <td>rb24.ir</td>
                        <td>popupads.ir</td>
                    </tr>
                    <tr>
                        <td>itpro.ir</td>
                        <td></td>
                        <td>mashreghnews.ir</td>
                        <td></td>
                        <td>kanape.ir</td>
                        <td>aviny.com</td>
                        <td>mci.ir</td>
                        <td>portaltvto.com</td>
                        <td>mebank.ir</td>
                        <td>nextpopup.ir</td>
                    </tr>
                    <tr>
                        <td>rtl-theme.com</td>
                        <td></td>
                        <td>jamnews.ir</td>
                        <td></td>
                        <td>plaan.ir</td>
                        <td>wisgoon.com</td>
                        <td>niniban.com</td>
                        <td>irandoc.ac.ir</td>
                        <td>ansarbank.com</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>bigtheme.ir</td>
                        <td></td>
                        <td>fararu.com</td>
                        <td></td>
                        <td>afarinak.ir</td>
                        <td>parsnaz.ir</td>
                        <td>tehran.ir</td>
                        <td>srbiau.ac.ir</td>
                        <td>bank-maskan.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>gadgetnews.ir</td>
                        <td></td>
                        <td>fardanews.com</td>
                        <td></td>
                        <td>appido.ir</td>
                        <td>caspiangc.ir</td>
                        <td>irancell.ir</td>
                        <td></td>
                        <td>postbank.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>parsfootball.com</td>
                        <td></td>
                        <td>irna.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>e-estekhdam.com</td>
                        <td></td>
                        <td>edbi.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>itbazar.com</td>
                        <td></td>
                        <td>alef.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>nic.ir</td>
                        <td></td>
                        <td>bim.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>shopkeeper.ir</td>
                        <td></td>
                        <td>iranjib.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>emalls.ir</td>
                        <td></td>
                        <td>bki.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>marketwp.ir</td>
                        <td></td>
                        <td>tnews.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>esam.ir</td>
                        <td></td>
                        <td>ttbank.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>gooyait.com</td>
                        <td></td>
                        <td>dana.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>netbarg.com</td>
                        <td></td>
                        <td>karafarinbank.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>lioncomputer.ir</td>
                        <td></td>
                        <td>jamejamonline.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>iranecar.com</td>
                        <td></td>
                        <td>sbank.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>parsine.com</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>cinematicket.org</td>
                        <td></td>
                        <td>sinabank.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>seratnews.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>post.ir</td>
                        <td></td>
                        <td>shahr-bank.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>khabarpu.com</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>parsonline.com</td>
                        <td></td>
                        <td>bank-day.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>vananews.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>ssaa.ir</td>
                        <td></td>
                        <td>refah-bank.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>mizanonline.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>rahvar120.ir</td>
                        <td></td>
                        <td>hibank24.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>hamshahrionline.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>khamenei.ir</td>
                        <td></td>
                        <td>izbank.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>aftabnews.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>eranico.com</td>
                        <td></td>
                        <td>ghbi.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>bamdad.net</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>samandehi.ir</td>
                        <td></td>
                        <td>middleeastbank.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>shomanews.com</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>alibaba.ir</td>
                        <td></td>
                        <td>ba24.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>rajanews.com</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>tax.gov.ir</td>
                        <td></td>
                        <td>cinoor.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>donya-e-eqtesad.com</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>zoodfood.com</td>
                        <td></td>
                        <td>askariye.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>rokna.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>niazerooz.com</td>
                        <td></td>
                        <td>rqbank.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>faradeed.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>modiseh.com</td>
                        <td></td>
                        <td>qmb.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>roozno.com</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>roham.ws</td>
                        <td></td>
                        <td>parsian-bank.ir</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>ilna.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>chmail.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>snn.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>lastsecond.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>tabnakbato.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>bayanbox.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>iribnews.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>adliran.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>parstoday.com</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>mihanstore.net</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>eghtesadonline.com</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>zanbil.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>saat24.com</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>irimo.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>bultannews.com</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>mobinnet.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>entekhab.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>hostiran.net</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>kimiaonline.com</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>manofile.com</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>mofidonline.com</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>ikco.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>tct.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>alodoctor.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>sahamyab.com</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>sabanet.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>asiatech.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>hiweb.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td style="direction: ltr;text-align: right">1544.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>time.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>shatel.ir</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>sanjesh.org</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </table>
            </div>
        </div>
</section>

